name: astro_common
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dio: ^5.4.3
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  test: ^1.25.7
  very_good_analysis: ^5.1.0
